polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^restricted/$', views.restricted, name='restricted'),
)

vip_gui/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/'

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls'))
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),
    )

rango/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from rango.models import Category, Page, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

    class Meta:
        model = Page
        exclude = ('category', )

rango/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from rango.forms import CategoryForm
from rango.forms import PageForm
from rango.models import Category
from rango.models import Page

def index(request):
    category_list = Category.objects.all()
    page_list = Page.objects.order_by('views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        if (datetime.now() - last_visit_time).seconds > 0:
            visits += 1
            reset_last_visit_time = True
    else:
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits
    context_dict['visits'] = visits

    return render(request, 'rango/index.html', context_dict)

def about(request):
    if request.session.get('visits'):
        count = request.session.get('visits')
    else:
        count = 0

    return render(request, 'rango/about.html', {'visits': count})

def category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name

        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages

        context_dict['category'] = category
        context_dict['category_name_slug'] = category_name_slug
    except Category.DoesNotExist:
        pass

    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    else:
        form = CategoryForm()

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                return category(request, category_name_slug)
        else:
            print(form.errors)
    else:
        form = PageForm()

    context_dict = {'form':form, 'category': cat}

    return render(request, 'rango/add_page.html', context_dict)

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

templates/rango/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>About</h1>
    </div>
    <div>
        <p></strong>.</p>
        <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'base.html' %}

{% block title %}Add a Category{% endblock %}

{% block body_block %}
    <form role="form" id="category_form" method="post" action="/rango/add_category/">
        <h2 class="form-signin-heading">Add a Category</h2>

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}

        <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
    </form>
{% endblock %}

templates/rango/add_page.html
{% extends 'base.html' %}

{% block title %}Add Page{% endblock %}

{% block body_block %}
{% if category %}
    <form role="form" id="page_form" method="post" action=".">
        <h2 class="form-heading">Add a Page to {{ category.name }}</h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div class="form-group">
            <label for="id_title">Title</label>
            <input type="text" class="form-control" id="id_title" maxlength="128" placeholder="Title" name="title">
        </div>
        <div class="form-group">
            <label for="id_url">URL</label>
            <input type="url" class="form-control" id="id_url" maxlength=200" placeholder="Including http://" name="url">
        </div>

        <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
    </form>
{% else %}
    <p>This category does not exist.</p>
{% endif %}

{% endblock %}

templates/rango/category.html
{% extends 'base.html' %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>{{ category_name }}</h1>
    </div>
    {% if category %}
        {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'add_page' category_name_slug %}">Add a New Page</a></br>
        {% endif %}
    {% else %}
        The specified category {{ category_name }} does not exist!
    {% endif %}

{% endblock %}

templates/rango/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
        {% if c == act_cat %}
        <li class="active">
        {% else %}
        <li>
        {% endif %}
            <a href="{% url 'category' c.slug %}">{{ c.name }}</a>
        </li>
    {% endfor %}

{% else %}
    <li><strong>There are no categories present.</strong></li>

    </ul>
{% endif %}

templates/rango/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Index{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        <div class="page-header">
            <h1>Rango says... hello {{ user.username }}!</h1>
    {% else %}
            <h1>Rango says... hello world!</h1>
    {% endif %}
        </div>

    <div class="row placeholders">
        <div class="col-xs-12 col-sm-6 placeholder">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Categories</h3>
                </div>
            </div>

            {% if categories %}
                <ul class="list-group-item">
                    {% for category in categories %}
                    <li class="list-group-item"><a href="{% url 'category' category.slug %}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>
        <div class="col-xs-12 col-sm-6 placeholder">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Pages</h3>
                </div>
            </div>

            {% if pages %}
                <ul class="list-group-item">
                    {% for page in pages %}
                    <li class="list-group-item"><a href="{{page.url}}">{{ page.title }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
        </div>

    <p> visits: {{ visits }}</p>
{% endblock %}

templates/rango/restricted.html
{% extends 'base.html' %}


    {% block title %}Restricted Page{% endblock %}


{% block body_block %}
    <div class="page-header">
        <h1>Restricted page</h1>
    </div>

    Since you're logged in, you can see this text!
{% endblock %}